package com.github.joraclista.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 * Created by Alisa
 * version 1.0.
 */
@DynamoDBTable(tableName = "Products")
@Data
public class Product {

    @DynamoDBHashKey
    private String id;

    private String merchantId;

    @DynamoDBVersionAttribute
    private Long version;

    private String status = "PUBLIC";

    private String title;

    private String description;

    private Date added = new Date();

    @DynamoDBAutoGeneratedTimestamp
    private Date modified;

    private List<String> categories;
    private String currency;
    private double price;


}